config/routes.rb
Ptuno::Application.routes.draw do

  resources :docs

  get "main/index"
  get "main/test"

  devise_for :users

  resources :adventures do
    resources :characters
    resources :docs
    resources :chapters do
      resources :comments
    end
  end

  resources :characters
  resources :comments
  resources :chapters

  root :to => "main#index"

end

app/models/doc.rb
class Doc < ActiveRecord::Base
  attr_accessible :adventure_id, :gdoclink, :history, :name, :user_id, :imglink


  belongs_to :adventure
  belongs_to :user
  
  validates_length_of :imglink, :in => 1..200, :allow_blank => true
  validates_length_of :gdoclink, :in => 1..200, :allow_blank => true
  validates :adventure_id, :name,  presence: true  
   



end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  # GET /docs
  # GET /docs.json
  before_filter :authenticate_user!, :only => :delete
  
  def create
      
      @adventure = Adventure.find(params[:adventure_id])
      @doc = @adventure.docs.create(params[:doc])
      

 
      @doc.user = current_user
      @doc.save
      redirect_to adventure_path(@adventure)
  end
  def new
    
    @adventure = Adventure.find(params[:adventure_id])
    @doc = @adventure.docs.new
    @doc.adventure.id = @adventure.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doc }
    end
  end


  def update
    @doc = Doc.find(params[:id])
    @adventure = @doc.adventure

    respond_to do |format|
      if @doc.update_attributes(params[:doc])
        format.html { redirect_to @doc, notice: 'doc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    
    @doc = Doc.find(params[:id])
    @adventure = @doc.adventure
    @doc.destroy
    redirect_to docs_path
  end
  
  def index
    if params[:adventure_id]
      @adventure = Adventure.find(params[:adventure_id])
      @docs = @adventure.docs.all
    else
      @docs = Doc.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @docs }
    end
  end
  def show
    @doc = Doc.find(params[:id])    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @adventures }
    end
  end
  def edit
    @doc = Doc.find(params[:id])
    @adventure = @doc.adventure
  end

end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_form.html.erb
<%= form_for([@adventure, @doc]) do |f| %>
  <% if @doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
      <% @doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nombre del archivo" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
  <%= f.label "link al documento gdocs" %><br />
  <%= f.text_field :gdoclink %>
  </div>
  <div class="field">
    <%= f.label "Descipción" %><br />
    <%= f.text_area :history %>
  </div>
  <div class="field">
    <%= f.label "Link a la imagen" %><br />
    <%= f.text_field :imglink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Editando documento</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @doc %> |
<%= link_to 'Volver', docs_path %>

app/views/docs/index.html.erb
<h1>Listado de documentos</h1>

<table class="table table-striped">
  <tr>
    <th>Adventure</th>
    <th>Nombre</th>
    <th>Descripion</th>
    <th>imagen</th>
    <th>Gdoclink</th>
    <th>User</th>
    <th></th>
    <th></th>
    
  </tr>

<% @docs.each do |doc| %>
  <tr>
    <td><%=  link_to doc.adventure.name, doc.adventure %></td>
    <td><%= link_to doc.name, doc_path(doc) %></td>
    <td><%= doc.history %></td>
    <td><%= doc.imglink %></td>
    <td><%= link_to doc.gdoclink, doc.gdoclink %></td>
    <td><%= doc.user_id %></td>
    <td><%= link_to 'Editar', edit_doc_path(doc) %></td>
    <td><%= link_to 'Borrar', doc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />
 <% if params[:adventure_id] %>
 <%= link_to 'Crear un nuevo documento', new_adventure_doc_path(@adventure) %><br />
 <% end %>

<% @docs.each do |doc| %>
<% if doc.gdoclink != ""%>
<h3><%= doc.name %></h3>
<iframe width="900" height="720" src=<%= doc.gdoclink%></iframe>
<% end %>
<% end %>

app/views/docs/new.html.erb
<h1>New doc</h1>

<%= render 'form' %>


<%= link_to 'Volver', docs_path %>

app/views/docs/show.html.erb
<h1>
  
  <%= link_to @doc.adventure.name, @doc.adventure  %>
</h1>

<h2>
  
  <%= @doc.name %>
</h2>

<p>
 
  <%= @doc.history %>
</p>

<p>
  <b>link a la imagen:</b>
  <%= @doc.imglink %>
</p>

<p>
  <b>Gdoclink:</b>
  <%= @doc.gdoclink %>
</p>
<% if @doc.gdoclink != ""%>

<iframe width="900" height="720" src=<%= @doc.gdoclink%></iframe>
<% end %>



<%= link_to 'Editar', edit_doc_path(@doc) %> |
<%= link_to 'Volver', docs_path %>