config/routes.rb
Ptuno::Application.routes.draw do

  resources :docs

  get "main/index"
  get "main/test"

  devise_for :users

  resources :adventures do
    resources :characters
    resources :docs
    resources :chapters do
      resources :comments
    end
  end

  resources :characters
  resources :comments
  resources :chapters

  root :to => "main#index"

end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
  attr_accessible :description, :mc, :name, :playing, :system, :photo, :imglink
  has_attached_file :photo, :default_url => "missing.png",
                    :url  => "/assets/products/:id/:style/:basename.:extension",
                  	:path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"
  has_many :chapters, :dependent => :destroy
  has_many :characters, :dependent => :destroy
  has_many :docs, :dependent => :destroy

  

  validates :description, :name, :system,  presence: true
  validates :name, uniqueness: true
  validates_length_of :imglink, :in => 1..200, :allow_blank => true
  validates_attachment_size :photo, :less_than => 2.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']



end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  # GET /adventures
  # GET /adventures.json

  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @adventures = Adventure.all
    
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @adventures }
    end
  end

  # GET /adventures/1
  # GET /adventures/1.json
  def show
    @adventure = Adventure.find(params[:id])
    @adventure.chapters.sort_by &:created_at

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @adventure }
    end
  end

  # GET /adventures/new
  # GET /adventures/new.json
  def new
    @adventure = Adventure.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @adventure }
    end
  end

  # GET /adventures/1/edit
  def edit
    @adventure = Adventure.find(params[:id])
  end

  # POST /adventures
  # POST /adventures.json
  def create
    @adventure = Adventure.new(params[:adventure])

    respond_to do |format|
      if @adventure.save
        format.html { redirect_to @adventure, notice: 'Adventure was successfully created.' }
        format.json { render json: @adventure, status: :created, location: @adventure }
      else
        format.html { render action: "new" }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /adventures/1
  # PUT /adventures/1.json
  def update
    @adventure = Adventure.find(params[:id])

    respond_to do |format|
      if @adventure.update_attributes(params[:adventure])
        format.html { redirect_to @adventure, notice: 'Adventure was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adventures/1
  # DELETE /adventures/1.json
  def destroy
    @adventure = Adventure.find(params[:id])
    @adventure.destroy

    respond_to do |format|
      format.html { redirect_to adventures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/views/adventures/_form.html.erb
<%= form_for @adventure, :html => { :multipart => true } do |f| %>
  <% if @adventure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>

      <ul>
      <% @adventure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nombre" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Sistema de juego" %><br />
    <%= f.text_field :system %>
  </div>
  <div class="field">
    <%= f.label "Descripción" %><br />
    <%= f.text_area :description %>
    <%= cktext_area :adventure, :description, :ckeditor => {:uiColor => "#dddddd", :toolbar => "mini"} %> 
  </div>
  <div class="field">
    <%= f.label "Master de la partida" %><br />
    <%= f.text_field :mc %>
  </div>
  <div class="field">
    <%= f.label "¿Esta en juego?" %><br />
    <%= f.check_box :playing %>
  </div>
  <div class="field">
    <%= f.label "Enlace a foto" %><br />
    <%= f.text_field :imglink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/adventures/edit.html.erb
<h1>Editando aventura</h1>

<%= render 'form' %>

<%= link_to 'Ver aventura', @adventure %> |
<%= link_to 'Volver al listado de aventuras', adventures_path %>

app/views/adventures/index.html.erb
<h1>Listado de aventuras</h1>

<table class="table table-bordered">
  <tr>
    <th>Nombre</th>
    <th>Sistema</th>
    <th>Descripción</th>
    <th>Master</th>
    <th>Estado</th>
    <% if current_user.try(:admin?)%>
    <th></th>
    <th></th>
    <% end %>
  </tr>

<% @adventures.each do |adventure| %>
  <tr>
    <td><%= link_to adventure.name, adventure %></td>
    <td><%= adventure.system %></td>
    <td><%= adventure.description %></td>
    <td><%= adventure.mc %></td>
    <% if adventure.playing? %>
        <td> Aventura en curso </td>
        <%else%>
        <td> Aventura finalizada </td>
        <%end%>
    <% if current_user.try(:admin?)%>
      <td><%= link_to 'Editar', edit_adventure_path(adventure) %></td>
      <td><%= link_to 'Borrar', adventure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>  
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva aventura', new_adventure_path %>

app/views/adventures/new.html.erb
<h1>Nueva Aventura</h1>

<%= render 'form' %>

<%= link_to 'Volver', adventures_path %>

app/views/adventures/show.html.erb
<div class="container-fluid">
     <div class="row-fluid">  
      <div class="span12">
       
      <h1><%=@adventure.name %></h1>
      <p>          
          <%= @adventure.description %>
      </p>
        <% if current_user.try(:admin?)%>
            <%= link_to 'Editar la partida', edit_adventure_path(@adventure) %> <br />
        <% end %>
      <p>
        <% if @adventure.imglink != "" %>
           <%= image_tag @adventure.imglink, :size => "400x400", class: "img-rounded" %> 
        <% end %>
      </p>  
      <p>
          <b>Ambientada en:  </b>
          <%= @adventure.system %>
      </p>
      <p>
          <b>Dirigida por:</b>
          <%= @adventure.mc %>
      </p>
      <p>
          <b>Estado de la partida: </b>
          <% if @adventure.playing? %>
             jugando 
          <% else %>
             terminada 
          <% end %>
      </p> 
      <div class="seccion">       
        <h3> <a> Protagonizada por: </a></h3>
        <div class="listado">
          <ul>
              <% @adventure.characters.each do |char| %>
              <div class="bloque">
                <li><a><%= char.name %></a></li>
                <div class="contenido"><%= char.history.html_safe %>
                  <p><%= link_to 'Editar', edit_character_path(char) %></p>  
                  </div>
              </div>
              <% end %>
          </ul>
          <p><%= link_to 'Nuevo Jugador', new_adventure_character_path(@adventure) %></p>
        </div>
      </div>
      <div class="seccion"> 
        <h3><a><%= "Archivos de la aventura" %></a></h3> 
        <div class="listado"> 
          <ul>
            <% @adventure.docs.each do |doc| %>
              <div class="bloque">
                <li><a><%= doc.name %></a></li></p>
                <div class="contenido">  
                  <p><%= doc.name %></p>
                  <iframe width="900" height="720" src=<%= doc.gdoclink %></iframe>
                  <p><%= link_to 'Editar', edit_doc_path(doc) %></p>                  
                </div>  
              </div>            
            <% end %>
          </ul>    
          <p><%= link_to 'Nuevo documento', new_adventure_doc_path(@adventure) %></p>  
        </div> 
      </div>   
      <div class="seccion">
        <h3><a>Diario de la aventura</a></h3>
          <div class="listado"> 
            <ol>
              <% @adventure.chapters.each do |chapter| %>
                <div class="bloque">  
                  <li ><h4><a><%= chapter.name %></a></li></h4>
                  <div class="contenido">
                    <%= chapter.body.html_safe %>                  
                    <p><%= link_to 'Editar', edit_chapter_path(chapter) %></p>
                  </div>
                </div>              
            <% end %>
            </ol> 
            <p><%= link_to 'Nuevo Capitulo', new_adventure_chapter_path(@adventure) %></p>
          </div>
        </div>
        <%= link_to 'Volver', adventures_path %>
      </div>
      </div>
    
</div>