config/routes.rb
Ptuno::Application.routes.draw do

  resources :docs

  get "main/index"
  get "main/test"

  devise_for :users

  resources :adventures do
    resources :characters
    resources :docs
    resources :chapters do
      resources :comments
    end
  end

  resources :characters
  resources :comments
  resources :chapters

  root :to => "main#index"

end

app/views/layouts/_header.html.erb

<header class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </a>
      <p class="brand"> <%=link_to "Punalada Tapera", root_url,  id: "logo"%> </p>
      <div class="nav-collapse collapse navbar-responsive-collapse">
        <ul class="nav">
          <li class="divider-vertical"></li> 
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Aventuras<b class="caret"></b></a>
            <ul class="dropdown-menu">          
              <% @adventures.each do |adventure| %>
                <li><%= link_to adventure.name, adventure %></li>
              <% end %>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Personajes<b class="caret"></b></a>
            <ul class="dropdown-menu">          
              <% @characters.each do |character| %>
                <li><%= link_to character.name, character %></li>
              <% end %>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Indices <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Aventuras", adventures_path %></li>
              <li><%= link_to "Diarios", chapters_path %></li>
              <li><%= link_to "Personajes", characters_path %></li>
              <li><%= link_to "Archivos", docs_path %></li>
            </ul>
          </li>
          <li><%= link_to "Wikirol", "http://wikirol.dominarelmundo.org" %></li>
          <li><%= link_to "Testing zone", main_test_path %></li>
      
        </ul>
        <!-- <form class="navbar-search pull-left" action="">
          <input type="text" class="search-query span2" placeholder="Search">
        </form> -->
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.email, root_url %></li> 
            <li><%= link_to "Desconectarse", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Date de alta", new_user_registration_path %></li><li><%= link_to "Logeate", new_user_session_path %></li>
          <% end %>        
        </ul>
      </div><!-- /navbar-colapse -->      
    </div><!-- /navbar-inner --> 
  </div><!-- /container -->   
</header><!-- /navbar -->

      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Punalada Tapera</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Quando' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister' rel='stylesheet' type='text/css'>
    
  </head>
  <body>
    <%= render 'layouts/header' %>
  	<div class="container-fluid">
  		<div class="span10">
        <p id="notice"><%= notice %></p>
               
        
        <%= yield %>
  		</div>
    </div>
  </body>
</html>